### ISSUE TITLE
[Question] Tilted or Rectangle Channels

### ISSUE THREAD

**Issue by jpreese** [hamfirst/UBChat#29]
![tab_compare](https://cloud.githubusercontent.com/assets/6980197/23448339/5897ea34-fe1e-11e6-8f03-950a9b343c42.png)

I've had more positive reviews for the rectangle than the tilted, but obviously its going to vary person to person. I'm personally in the rectangle camp, but @hamfirst will obviously have the final say.

**Comment by hamfirst** [comment]
Eh I still prefer the skewed ones
